In [1]:
from src.counterfactuals._cadex import Cadex
from src.counterfactuals.visualization import compare
from data.GermanData import GermanData
from tensorflow import keras

2021-12-21 04:26:42.199774: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-21 04:26:42.199828: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
german_data = GermanData('data/input_german.csv', 'data/labels_german.csv')
model = keras.models.load_model('models/model_german')
test_X = german_data.X_test.iloc[6]
cadex = Cadex(model)
cf = cadex.generate(test_X)

2021-12-21 04:26:44.014048: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-12-21 04:26:44.014116: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2021-12-21 04:26:44.014137: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntu): /proc/driver/nvidia/version does not exist
2021-12-21 04:26:44.014350: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


<tf.Variable 'Variable:0' shape=(1, 61) dtype=float64, numpy=
array([[ 0.25989475, -0.71941474,  0.92825177,  0.12958415, -0.83635682,
        -0.71598666, -0.41802276, -0.59467462, -0.60623541, -0.24413654,
         1.19034383, -0.22331316, -0.64881365, -0.30966177,  0.94406194,
        -0.20412415, -0.33794397, -0.54267705, -0.34931309, -0.11250879,
        -0.22021079, -0.4744627 , -0.10666772,  1.62879343, -0.15597367,
        -0.10050378,  3.        , -0.25264558, -1.23436595, -0.2353911 ,
        -0.4744627 , -0.66050413, -0.23241869,  3.20431048, -1.11960758,
        -0.21389632, -0.2353911 ,  0.32634444,  1.84271658, -0.7117523 ,
        -0.63910148, -0.41388776, -0.40137644,  0.47841263, -0.22331316,
        -0.34479141,  0.64298333, -0.47841263, -0.41388776,  0.78288136,
        -0.14734777, -0.51946248, -1.22156123,  1.22156123, -0.19738551,
         0.19738551, -0.7117523 ,  2.18068698, -0.45857109, -0.58119931,
        -0.26094212]])>
tf.Tensor(
[[ 1.72252741  0.70393778  

In [3]:
df = compare(test_X, cf)
df

X        X'    change
duration               0.259895  1.722527  1.462633
installment_percent    0.928252  2.374997  1.446745
savings_< 100 DM      -1.234366  0.287175  1.521541
credit                -0.719415  0.703938  1.423353
account_status_< 0 DM -0.606235  0.854685  1.460920

In [4]:
test_X = german_data.input.iloc[6]
cadex = Cadex(model, transform=german_data.scale, inverse_transform=german_data.unscale)
cf = cadex.generate(test_X)
compare(test_X, cf)

<tf.Variable 'Variable:0' shape=(1, 61) dtype=float64, numpy=
array([[0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475, 0.25989475, 0.25989475, 0.25989475, 0.25989475,
        0.25989475]])>
tf.Tensor(
[[0.25989475 0.25989475 0.25989475 0.25989475 0.25989475 0.25989475
  0.25989475 0.25989

X    X'  change
sex_status_female: divorced/separated/married          0  24.0    24.0
savings_100..500 DM                                    0  24.0    24.0
savings_>= 1000 DM                                     0  24.0    24.0
savings_unknown/ no savings account                    0  24.0    24.0
sex_status_male: divorced/separated                    0  24.0    24.0
sex_status_male: married/widowed                       0  24.0    24.0
debtors_co-applicant                                   0  24.0    24.0
debtors_guarantor                                      0  24.0    24.0
property_car or other, not in attribute 6              0  24.0    24.0
property_real estate                                   0  24.0    24.0
property_unknown / no property                         0  24.0    24.0
other_installment_plans_bank                           0  24.0    24.0
other_installment_plans_stores                         0  24.0    24.0
housing_for free                                       0  24.0    24.0
housing_rent                                           0  24.0    24.0
job_management/self-employed                           0  24.0    24.0
job_unemployed/unskilled - non-resident                0  24.0    24.0
job_unskilled - resident                               0  24.0    24.0
phone_yes, registered under the customers name         0  24.0    24.0
foreign_no                                             0  24.0    24.0
employment_1..4 years                                  0  24.0    24.0
employment_4..7 years                                  0  24.0    24.0
employment_< 1 year                                    0  24.0    24.0
savings_< 100 DM                                       0  24.0    24.0
employment_unemployed                                  0  24.0    24.0
purpose_retraining                                     0  24.0    24.0
purpose_car (used)                                     0  24.0    24.0
account_status_>= 200 DM                               0  24.0    24.0
credit_history_critical account                        0  24.0    24.0
credit_history_delay in paying off in the past         0  24.0    24.0
account_status_< 0 DM                                  0  24.0    24.0
credit_history_no credits taken                        0  24.0    24.0
purpose_business                                       0  24.0    24.0
purpose_car (new)                                      0  24.0    24.0
account_status_0..200 DM                               0  24.0    24.0
credit_history_all credits at this bank paid ba...     0  24.0    24.0
purpose_domestic appliances                            0  24.0    24.0
purpose_education                                      0  24.0    24.0
purpose_others                                         0  24.0    24.0
purpose_radio/television                               0  24.0    24.0
purpose_repairs                                        0  24.0    24.0
job_skilled employee / official                        1  24.0    23.0
foreign_yes                                            1  24.0    23.0
existing_credits                                       1  24.0    23.0
phone_none                                             1  24.0    23.0
employment_>= 7 years                                  1  24.0    23.0
people_maintained                                      1  24.0    23.0
other_installment_plans_none                           1  24.0    23.0
account_status_no checking account                     1  24.0    23.0
housing_own                                            1  24.0    23.0
savings_500..1000 DM                                   1  24.0    23.0
credit_history_existing credits paid back duly ...     1  24.0    23.0
property_building society savings agreement            1  24.0    23.0
debtors_none                                           1  24.0    23.0
sex_status_male: single                                1  24.0    23.0
purpose_furniture/equipment                            1  24.0    23.0
installm

In [5]:
test_X = german_data.X_test.iloc[10]
cadex = Cadex(model, n_changed=8)
cf = cadex.generate(test_X)
compare(test_X, cf)

<tf.Variable 'Variable:0' shape=(1, 61) dtype=float64, numpy=
array([[-0.24272201, -0.87066782,  0.92825177,  1.03103909,  0.04136252,
        -0.71598666,  2.39221426,  1.68159186, -0.60623541, -0.24413654,
        -0.84009341, -0.22331316,  1.54127461, -0.30966177, -1.05925253,
        -0.20412415, -0.33794397,  1.84271658, -0.34931309, -0.11250879,
        -0.22021079, -0.4744627 , -0.10666772, -0.6139514 , -0.15597367,
        -0.10050378, -0.33333333, -0.25264558,  0.81013252, -0.2353911 ,
        -0.4744627 , -0.66050413, -0.23241869, -0.31207962,  0.89317009,
        -0.21389632, -0.2353911 ,  0.32634444, -0.54267705,  1.40498317,
        -0.63910148, -0.41388776,  2.49142674, -2.0902458 , -0.22331316,
        -0.34479141,  0.64298333, -0.47841263, -0.41388776,  0.78288136,
        -0.14734777, -0.51946248, -1.22156123,  1.22156123, -0.19738551,
         0.19738551, -0.7117523 , -0.45857109, -0.45857109,  1.72058015,
        -0.26094212]])>
tf.Tensor(
[[-2.42722013e-01 -8.706678

X        X'    change
property_car or other, not in attribute 6  1.404983  1.745699  0.340716
other_installment_plans_none              -2.090246 -1.741953  0.348293
account_status_no checking account        -0.840093 -0.484096  0.355997
property_real estate                      -0.639101 -0.282570  0.356532
job_unskilled - resident                  -0.519462 -0.167815  0.351648
purpose_car (used)                        -0.349313  0.000673  0.349986
sex_status_male: married/widowed          -0.312080  0.012480  0.324559
foreign_no                                -0.197386  0.132683  0.330069

In [6]:
model.predict(test_X.to_numpy())

ValueError: in user code:

    File "/home/ztrafas/PycharmProjects/counterfactuals/venv/lib/python3.8/site-packages/keras/engine/training.py", line 1621, in predict_function  *
        return step_function(self, iterator)
    File "/home/ztrafas/PycharmProjects/counterfactuals/venv/lib/python3.8/site-packages/keras/engine/training.py", line 1611, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/home/ztrafas/PycharmProjects/counterfactuals/venv/lib/python3.8/site-packages/keras/engine/training.py", line 1604, in run_step  **
        outputs = model.predict_step(data)
    File "/home/ztrafas/PycharmProjects/counterfactuals/venv/lib/python3.8/site-packages/keras/engine/training.py", line 1572, in predict_step
        return self(x, training=False)
    File "/home/ztrafas/PycharmProjects/counterfactuals/venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/home/ztrafas/PycharmProjects/counterfactuals/venv/lib/python3.8/site-packages/keras/engine/input_spec.py", line 227, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" '

    ValueError: Exception encountered when calling layer "sequential" (type Sequential).
    
    Input 0 of layer "dense" is incompatible with the layer: expected min_ndim=2, found ndim=1. Full shape received: (None,)
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None,), dtype=float32)
      • training=False
      • mask=None
